spring:
  profiles:
    active: default
---
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/community
    username: woo
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  flyway:
    baseline-on-migrate: true
  thymeleaf:
    cache: false

logging.level:
  org:
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create

  flyway:
    baseline-on-migrate: false