spring:
  profiles:
    active: default
---
spring:
  profiles: default
  servlet:
    multipart:
      location: C:\upload
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/community
    username: woo
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  flyway:
    baseline-on-migrate: true
  thymeleaf:
    cache: false

logging.level:
  org:
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace

server:
  error:
    include-exception: true
    include-stacktrace: always
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    enabled: false